SELECT BDATE,ADDRESS FROM EMPLOYEE WHERE FNAME = 'John' AND MINIT = 'B' AND LNAME = 'Smith';

SELECT E.FNAME || ' ' || E.MINIT || '. ' || E.LNAME AS NAME, E.ADDRESS FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DNO = D.DNUMBER WHERE D.DNAME = 'Research'; 

SELECT P.PNUMBER,D.DNUMBER,E.LNAME,E.ADDRESS,E.BDATE FROM PROJECT P,DEPARTMENT D,EMPLOYEE E WHERE P.DNUM = D.DNUMBER AND D.MGR_SSN = E.SSN AND P.PLOCATION = 'Stanford';

WITH SUPERVISOR AS (SELECT FNAME AS SUPERVISOR_FNAME, LNAME AS SUPERVISOR_LNAME,SSN FROM EMPLOYEE)
SELECT E.FNAME AS SUPERVISEE_FNAME,E.LNAME AS SUPERVISEE_LNAME,S.SUPERVISOR_FNAME,S.SUPERVISOR_LNAME FROM EMPLOYEE E LEFT JOIN SUPERVISOR S ON E.SUPER_SSN = S.SSN;

